name: snapshot

on:
    pull_request:
    push:

jobs:
    build_test:
        runs-on: ubuntu-latest
        steps:
        -
            name: Checkout
            uses: actions/checkout@v2
            with:
                fetch-depth: 0
        -
            name: Set up Go
            uses: actions/setup-go@v1
            with:
                go-version: 1.13.x
        -
            name: Prepare build vars
            id: build_vars
            run: |
                echo ::set-output name=build_commit::${{ github.sha }}
                echo ::set-output name=build_time::$(date -u +"%Y-%m-%dT%H:%M:%S")
                echo ::set-output name=build_version::$(git describe --tags 2>/dev/null || echo "v0.0.0")
        -
            name: Build using goreleaser
            uses: goreleaser/goreleaser-action@v1
            with:
                version: latest
                args: release --snapshot --rm-dist
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                BUILD_COMMIT: ${{ steps.build_vars.outputs.build_commit }}
                BUILD_TIME: ${{ steps.build_vars.outputs.build_time }}
                BUILD_VERSION: ${{ steps.build_vars.outputs.build_version }}
        -
            name: output
            run: |
                echo $(pwd)
                ./dist/testing-actions-go_linux_amd64/testing-actions-go

    unit_test:
        runs-on: ubuntu-latest
        needs: [build_test]
        steps:
        -
            name: output
            run: |
                echo $(pwd)
                ./dist/testing-actions-go_linux_amd64/testing-actions-go

